# Generated by Django 6.0.6 on 2026-07-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0008_quiz_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("Multiple Choice", "Multiple Choice"),
                    ("True/False", "True/False"),
                    ("Fill In the Blank", "Fill In the Blank"),
                    ("Fill In Multiple Blanks", "Fill In Multiple Blanks"),
                    ("Multiple Answers", "Multiple Answers"),
                    ("Multiple Dropdowns", "Multiple Dropdowns"),
                    ("Matching", "Matching"),
                    ("Numerical Answer", "Numerical Answer"),
                    ("Formula Question", "Formula Question"),
                    ("Essay Question", "Essay Question"),
                    ("File Upload Question", "File Upload Question"),
                    ("Text (no question)", "Text (no question)"),
                    ("multiple_choice_question", "Multiple Choice"),
                    ("true_false_question", "True/False"),
                    ("essay_question", "Essay"),
                    ("formula_question", "Formula"),
                    ("one_word_question", "One Word"),
                    ("fill_in_the_blank_question", "Fill in the Blank"),
                ],
                max_length=30,
            ),
        ),
    ]
