# Generated by Django 6.0.6 on 2026-07-05 16:19

from django.db import migrations, models


def migrate_legacy_quiz_statuses(apps, schema_editor):
    Quiz = apps.get_model("quiz", "Quiz")
    Quiz.objects.filter(status__in=["DRAFT", "PUBLISHED"]).update(status="READY")


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0009_alter_question_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="quiz",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="security_answer",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="security_question",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first_pet", "What was your first pet's name?"),
                    ("birth_city", "What city were you born in?"),
                    ("first_school", "What was the name of your first school?"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="status",
            field=models.CharField(
                choices=[
                    ("READY", "Ready"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                ],
                default="READY",
                max_length=10,
            ),
        ),
        migrations.RunPython(migrate_legacy_quiz_statuses, noop_reverse),
    ]
